name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: Lint and Test on Node 16
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
          - 20

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn run test
